yarnPath: ".yarn/releases/yarn-berry.cjs"
nodeLinker: node-modules
enableInlineBuilds: true
# npmRegistryServer: https://registry.npm.taobao.org
# ${ELECTRON_MIRROR}: http://npm.taobao.org/mirrors/electron/
